# Generated by Django 4.2.6 on 2023-10-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsu_anon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuser',
            name='client_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
