# Generated by Django 4.2.6 on 2023-11-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsu_anon_app', '0002_alter_anonuser_client_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonuser',
            name='client_ip',
        ),
    ]
