# Generated by Django 4.2.6 on 2023-11-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsu_anon_app', '0003_remove_anonuser_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonuser',
            name='client_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
